core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

rps/urls.py
from django.contrib import admin
from django.urls import path,include

from core.views import index, score,signup


urlpatterns = [
    path('', include('core.urls')),
    path('score/',score, name='score'),
    path("admin/", admin.site.urls),
    # path('signup/', signup, name='signup'),

]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
    'placeholder': 'Your username',
    'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

core/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .forms import SignupForm

@login_required
def index(request):
    return render(request, 'core/index.html')

@login_required
def score(request):
    return render(request, "core/score.html")

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })

core/templates/core/base.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock %} {{ user.username }}</title>
    </head>
    
    <body class="bg-gray-200">
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <a href="{% url 'core:index' %}" class="text-xl font-semibold">R-P-S</a>

            <div class="space-x-6">

                {% if request.user.is_authenticated %}
                <a href="{% url 'score' %}" class="text-lg font-semibold hover:text-gray-500">Score</a>
                <a href="{% url 'core:logout' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Log Out</a>
                {% else %}
                <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
                {% endif %}
            </div>
        </nav>



        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>



        <footer class="py-6 px-6 flex justify-between bg-gray-800 w-full fixed bottom-0">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>

                <p class="text-lg text-gray-500">Falana Dhimkana. Lorem ipsum bla bla bla.</p>
            </div>
            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

                <ul class="space-y-2">
                    <!-- <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li> -->
                    <li><a href="https://wrpsa.com/the-official-rules-of-rock-paper-scissors/" class="text-lg text-teal-500 hover:text-teal-700">Rules</a></li>
                    <li><a href="https://en.wikipedia.org/wiki/Rock_paper_scissors" class="text-lg text-teal-500 hover:text-teal-700">How to play</a></li>
                </ul>
            </div>
        </footer>
    </body>
    
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %} Welcome {% endblock %}

{% block content %}


    {% if user.is_authenticated %}
    {% load static %}
        <div class="bg-white p-6 rounded-lg shadow-md text-center">
            <h1 class="text-2xl font-semibold mb-4">Rock Paper Scissors</h1>
            <div class="flex justify-center mb-4">
                <div class="flex justify-center mb-4">
                    <div class="text-center w-32">
                        <p class="text-gray">Computer</p>
                        <img id="comp-choice" src="{% static 'images/scissor.png' %}" alt="Computer's choice" class="w-32">
                    </div>
                    <div class="text-center w-32">
                        <p class="text-gray">User</p>
                        <img id="user-choice" src="{% static 'images/scissor-user.png' %}" alt="User's choice" class="w-32">
                    </div>
                </div>
                <div class="text-xl font-bold absolute top-0 right-0 mt-24 mr-10">
                    <div class="flex items-center justify-center">
                        <span class="text-blue-600">User: </span><span id="user-score" class="ml-2">0</span>
                    </div>
                    <div class="flex items-center justify-center">
                        <span class="text-red-600">Computer: </span><span id="comp-score" class="ml-2">0</span>
                    </div>
                </div>
            </div>

            <div class="flex justify-center mb-4">
                <button id="rock" class="btn bg-red-400 hover:bg-red-500 text-white font-semibold py-2 px-4 rounded-md mr-2">Rock</button>
                <button id="paper" class="btn bg-yellow-400 hover:bg-yellow-500 text-white font-semibold py-2 px-4 rounded-md mr-2">Paper</button>
                <button id="scissor" class="btn bg-green-400 hover:bg-blue-600 text-white font-semibold py-2 px-4 rounded-md">Scissors</button>
            </div>



            <div id="message" class="text-xl font-bold"></div>


            <div class="text-xl font-bold flex justify-center mt-4">
                <div class="flex items-center justify-center">
                    <span class="text-blue-800">Points: </span><span id="comp-points" class="ml-2">0</span>
                </div>
                <div class="flex items-center justify-center ml-4">
                    <span class="text-blue-800">Points: </span><span id="user-points" class="ml-2">0</span>
                </div>
                
            </div>

            <div class="flex justify-center mt-4">
                <button id="reset" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">Reset</button>
            </div>
        </div>

        <script src="{% static 'js/script.js' %}"></script>
    {% else %}
        <script>
            window.location.replace("{% url 'core:login' %}");
        </script>
    {% endif %}


{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

core/templates/core/score.html
{% extends 'core/base.html' %}

{% block title %} Score {% endblock %}

{% block content %}
    <h1>The score board</h1>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl"  style="margin-bottom: 100px;">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
    
</div>
{% endblock %}